### PR TITLE
Support for multi-platform builds

### PR DESCRIPTION
**Pull request by zdmytriv**
## what
* Introduced new input parameter `--platform`

## why
* Support for multi-platform docker builds

## references
- https://github.com/docker/setup-qemu-action/
- https://docs.docker.com/build/ci/github-actions/multi-platform/

### CODE REVIEW

**Review by korenyoni — APPROVED** [review]

**Comment by korenyoni** [comment]
LGTM, the main buildx nuances are in parameters that you guys aren't overriding and are keeping the defaults

* docker/setup-buildx-action: `driver`, `driver-opts`
* docker-build-push-action: `output`

**Comment by zdmytriv** [comment]
> LGTM, the main buildx nuances are in parameters that you guys aren't overriding and are keeping the defaults
> 
> * docker/setup-buildx-action: `driver`, `driver-opts`

Even tho I think eventually it would be nice to allow parameterizing of buildx github action but it shouldn't be part of this PR. This enhancement would be related to buildx itself and not to multi-platform build support with qemu.

**Comment by korenyoni** [comment]
Sorry I meant that there is an input in `docker-build-push-action` named `output` which controls the `buildx` `--output` flag, and it's the most complicated flag in buildx. What I meant was if you are not touching that input, then there is nothing to worry about and this PR is totally safe in all cases.

**Comment by zdmytriv** [comment]
Thanks for your explanation.

**Pull request merged**
